apiVersion: v1
kind: Pod
metadata:
  name: sample-app
  labels:
    app: sample-app
spec:
  containers:
  - name: app
    image: busybox
    command:
    - sh
    - -c
    - |
      while true
      do
        echo "$(date) INFO Payment processed"
        sleep 5
      done