apiVersion: v1
kind: Pod
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  containers:
  - name: inventory-service
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "inventory-service started"
        while true; do
          echo "Calling payment-service..."
          sleep 1
        done