apiVersion: v1
kind: Pod
metadata:
  name: payment-service
spec:
  containers:
  - name: payment-service
    image: busybox
    command:
      - sh
      - -c
      - |
        echo "Using token from Kubernetes Secret..."
        echo "401 Unauthorized"
        echo "Token validation failed"
        sleep 3600